Codegen.mo - got rid of unused import Inst;
Inst.mo
- fixed problem with the inner(mod) <-> inner outer (mod)
  for the example model in the Modelica Specification:
  5.5 Simultaneous Inner/Outer Declarations
  see testsuite/mofiles/InnerOuterSystem.mo
- better instantiation caching (both partial and full is now cached)
- fixed the bug that generated error:
  Error: Variable s: In modifier (s), class or component s, not found in the built-in class Real
  Error: Variable s: In modifier (start = 0.1), class or component start, not found in the built-in class Real
  by commenting out: // compModLocal = Mod.lookupCompModification12(mod,n); 
  in Inst.addComponentsToEnv, see testsuite/mosfiles/ModifierProblem.mos.

Mod.mo
- commented out unused code in Mod.unelabMod
- trivial text change

SCode.mo
- SCode.modEqual is now public

SimCode.mo
- commented out unused import Print;


Added tests for checking 2 bug fixes in Inst.mo:
testsuite/mofiles/InnerOuterSystem.mo 
testsuite/mofiles/ModifierProblem.mo  
testsuite/mosfiles/ModifierProblem.mo
testsuite/mosfiles/ModifierProblem.mos



git-svn-id: https://openmodelica.org/svn/OpenModelica/trunk@4871 f25d12d1-65f4-0310-ae8a-bbce733d8d8e