- use cref because #define A.B is not allowed because of "." error C2008 (Visual Studio)
git-svn-id: https://openmodelica.org/svn/OpenModelica/trunk@8101 f25d12d1-65f4-0310-ae8a-bbce733d8d8e